### ISSUE TITLE
Can be done without C code

### ISSUE THREAD

**Issue by decibel** [theory/colnames#2]
FWIW, as of 9.3 you can do this without C code by using row_to_json() and then listing all the keys. Might be worth mentioning in the docs/readme since a lot of people can't use C functions.

**Comment by theory** [comment]
Care to submit a PR?

**Comment by decibel** [comment]
You mean a patch? I thought this was a PR ;P

**Comment by theory** [comment]
A pull request is a patch that's been submitted via GitHub's pull request mechanism. So yeah.

**Comment by decibel** [comment]
Ahh, Pull Request, not Problem Report! I'll put one together.
